### ISSUE TITLE
deploy scripts

### ISSUE THREAD

**Issue by tabshaikh** [RiftLend/monorepo-v1#21]

**Comment by floor-licker** [comment]
Hey @tabshaikh 
If I could get a more detailed description of this issue I could potentially start working on it.

**Comment by tabshaikh** [comment]
@floor-licker this is a mega issue wherein we have to write the deploy scripts for the whole protocol so that we can start deploying on various chains. Check out the deployment scripts of https://github.com/aave/protocol-v2/tree/master/tasks/full . They are written in TS but we would like to have them written in forge

**Comment by tabshaikh** [comment]
closed by this commit https://github.com/RiftLend/monorepo-v1/commit/dc54c760ab6634450bafb78a6441ac5bffb62a49
